on:
  schedule:
    - cron: '30 12 * * *'
  push:
    branches:
      - master

jobs:
  update_upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: upstream
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote add upstream https://github.com/cbuijs/ripe-geo
          git fetch upstream
          git restore --source upstream/master *
          git add -u
          git commit -m "$(git log --format=%B -n 1 upstream/master)"
          git push

  update_continents:
    needs: update_upstream
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: continents
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge origin/upstream
          git push
